### ISSUE TITLE
Bug sur gartic phone

### ISSUE THREAD

**Issue by lixyrat** [IV2FI/DrawBot#10]
Le bot ne fini pas le travaille il ne mets que la structure je dois faire quoi ?

**Comment by IV2FI** [comment]
Jamais eu ce problème, c'est bizarre. Essaye de réduire la vitesse peut être et refais le set up

**Comment by lixyrat** [comment]
Ok je vais essayer

**Comment by lixyrat** [comment]
Je vien d'essayez mais le bot ne capte que le noure et le jaune

**Comment by lixyrat** [comment]
Merci j'ai trouvé
