### ISSUE TITLE
[DL] Virus détecté au dl

### ISSUE THREAD

**Issue by HugoLeBoennec** [IV2FI/DrawBot#11]
Virus détecté au téléchargement de la 10.1 sur chrome
Virus detected on 1.01 release download on chrome

Chrome : Version 89.0.4389.114

**Comment by RedLine33100** [comment]
Cela est normal, cela doit être dues à l'utilisation de la souris

**Comment by IV2FI** [comment]
C'est ainsi avec les .exe qui sortent de nul part. Tu peux faire l'expérience chez toi :

Crée un fichier python test.py
Fais juste un print dans ce fichier : print("ok")
Apres avoir installé pyinstaller, fais pyinstaller test.py pour générer le exe
Upload l'exe sur un site scannant les virus
Le site te dira que c'est un Trojan alors que c'est juste un print...

**Comment by XiominTSS** [comment]
plot twist: C'est juste son plan maléfique

**Comment by OriCoding** [comment]
Ma dja sortie la mm excuse ''utilisation dla sourie''
