### ISSUE TITLE
Y'a un Trojan dedans

### ISSUE THREAD

**Issue by XiominTSS** [IV2FI/DrawBot#12]
Mon navigateur me mets "Virus Détecté". Windows Defender me mets un: Trojan:Script/Conteban.A!ml donc je crois pas que c'est très sécurisé

**Comment by IV2FI** [comment]
Voir https://github.com/IV2FI/DrawBot/issues/11#issuecomment-817004646

**Comment by XiominTSS** [comment]
Ah!
D'accord!
Mais sinon, pourquoi y'a un virus "Backdoor" dans la version 1.0.0?
