### ISSUE TITLE
Mauvaise reconnaissance des couleurs

### ISSUE THREAD

**Issue by XiominTSS** [IV2FI/DrawBot#14]
Comparaison
![image](https://user-images.githubusercontent.com/84149666/118183447-69bc8f00-b43a-11eb-84ae-49fc378027e9.png)
![image](https://user-images.githubusercontent.com/84149666/118183461-6de8ac80-b43a-11eb-9d6c-4be81ffd53bc.png)

**Comment by XiominTSS** [comment]
J'ai essayé de changer plein de trucs, mais rien n'a marché

**Comment by IV2FI** [comment]
Je n'ai pas de probleme de couleurs avec ton image, c'est bien en jaune chez moi.
Le problème vient donc de ton setup. Reregarde bien la vidéo tuto et n'oublie pas de redémarrer l'application une fois le setup terminé
