### ISSUE TITLE
DrawBot falsely marked as a computer virus by Windows Defender? (DrawBot faussement marqué comme un virus informatique par Windows Defender ?)

### ISSUE THREAD

**Issue by SuperServiech** [IV2FI/DrawBot#16]
[English:]

Hello,

I was downloading DrawBot zip file and when I was trying to extract it, Windows Defender blocked it and recognized it as a  Trojan of some sort?? [https://i.imgur.com/eRlSfvS.png] I know this is a open-source program but I'm still quite concerned because I have little to no experience in Coding. Can you please assure me if this is a false alarm?

Thank you.

[French:]

Je téléchargeais le fichier zip DrawBot et lorsque j'essayais de l'extraire, Windows Defender l'a bloqué et l'a reconnu comme un cheval de Trojan ??[https://i.imgur.com/eRlSfvS.png]  Je sais qu'il s'agit d'un programme open source mais je suis toujours assez inquiet car j'ai peu ou pas d'expérience en codage. Pouvez-vous m'assurer s'il s'agit d'une fausse alerte ?

Merci.

**Comment by IV2FI** [comment]
Hello,

Yes it's safe, there's no virus in it. I mean, I'm the one who coded it, so I don't know why you would trust me, but I assure you there's nothing in it.
