### ISSUE TITLE
Only drawing with dark color

### ISSUE THREAD

**Issue by ClaudioPanConQueso** [IV2FI/DrawBot#17]
lmao it only draws with 1 color, dark. i also restarted my pc but idk what happens

**Comment by ClaudioPanConQueso** [comment]
fixed, i didn't do anything but it draws with color

**Comment by ClaudioPanConQueso** [comment]
Nope, it only uses dark color

**Comment by IV2FI** [comment]
did you watch the tutorial for the set up? if you are using it with paint, it's not working properly on it, so it is expected. other websites should work

**Comment by ClaudioPanConQueso** [comment]
i did the tutorial for set up, it works nice now, sorry. i have a tiny brain
