### ISSUE TITLE
Вау ахуеть как же все понятно спасибо большое за скрипт чел

### ISSUE THREAD

**Issue by VityaSchel** [IV2FI/DrawBot#29]
![image](https://user-images.githubusercontent.com/59040542/175986084-a73da4bd-0a46-4358-a498-228678cde244.png)

реально топ очень нравится кстати как насчет того чтобы выучить английский и делать блять на английском интерфейс или хотя бы добавить смену языка пидорасина пошел нахуй

**Comment by IV2FI** [comment]
No need to be this upset. I did this for a french YouTube video, so it makes sense that I wrote the UI in french and didn't bother with any translation. However, I did a full tutorial in English, so you should be able to figure things out with it: https://youtu.be/bdCBftJV25s

Hope this helps

**Comment by LeakedSoftware** [comment]
ты ебанат там видос на англ есть

**Comment by VityaSchel** [comment]
> ты ебанат там видос на англ есть

Как тебе смайлик клоуна поставить чертила 🥵🥵🥸🥸🤠🤬🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡😡😡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡😸🤡🤡🤡🤡🤡

**Comment by 9merci** [comment]
> > ты ебанат там видос на англ есть
> 
> Как тебе смайлик клоуна поставить чертила 🥵🥵🥸🥸🤠🤬🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡😡😡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡😸🤡🤡🤡🤡🤡

хахазаза ебать ты злой ребенок
