### ISSUE TITLE
SkribblColor 

### ISSUE THREAD

**Issue by Saku241** [IV2FI/DrawBot#3]
Il semblerait que tu aies oublié une ligne de couleur pour la palette Skribbl ?
`255 255 255 193 193 193 239 19 11 255 113 0 255 228 0 0 204 0 0 178 255 35 31 211 163 0 186 211 124 170 160 82 45`

Il y a 11 couleurs actuellement alors que la palette skribbl compte 22 couleurs, une ligne a certainement été oubliée

**Comment by IV2FI** [comment]
Y’a le bon nombre dans le code source mais en effet, ils manquent des couleurs dans le zip à télécharger dans la release, je regarderai ça ce soir pour corriger ça

**Comment by IV2FI** [comment]
Effectivement, bien vu ! Merci beaucoup !
C'est corrigé
