### ISSUE TITLE
Image not showing correctly (gartic)

### ISSUE THREAD

**Issue by Triston3291** [IV2FI/DrawBot#35]
So it will take an image and draw it just fine, but for some reason when the actual game ends and shows the albums the drawing doesn't show (well it does but barely)
while drawing:
![image_2024-02-05_170312116](https://github.com/IV2FI/DrawBot/assets/159082023/19049407-cbc1-4794-aff2-105a42a7eca9)
after drawing: 
![image_2024-02-05_170346063](https://github.com/IV2FI/DrawBot/assets/159082023/564a4575-8503-43d4-bab2-3343fc4782c7)

**Comment by IV2FI** [comment]
I think they patched the website so you can't use bots anymore

**Comment by Triston3291** [comment]
Ah, well that sucks
