### ISSUE TITLE
Trojan:Win32/Ymacco.AA27

### ISSUE THREAD

**Issue by Square04299** [IV2FI/DrawBot#4]
Apres avoir dézipper le dossier DrawBot, windows interviens pour me dire qu'il y a un trojan dans l'element DrawBot.exe

Un oublie, une erreur ou quelque chose d'autre ?

![image_2021-04-01_162228](https://user-images.githubusercontent.com/25258309/113308433-72cc2380-9306-11eb-8e9f-dd55c4930e48.png)

**Comment by IV2FI** [comment]
C'est ainsi avec les .exe qui sortent de nul part. Tu peux faire l'expérience chez toi :
- Crée un fichier python test.py
- Fais juste un print dans ce fichier : print("ok")
- Apres avoir un installé pyinstaller, fais pyinstaller test.py pour générer le exe
- Upload l'exe sur un site scannant les virus

Le site te dira que c'est un Trojan alors que c'est juste un print...
