### ISSUE TITLE
Ajout d'une fonction stop & autre.

### ISSUE THREAD

**Issue by FinishtT** [IV2FI/DrawBot#5]
**Yop!** ta vidéo ma beaucoup plus car:
Personnellement je boss sur un projet nommé **FARMING BOT POKEMMO** et je joue avec le **GETPIXEL**
Du coup ton projet ma beaucoup touché :)

Pourquoi pas une **fonction** permettant de **STOP** le bot (car oui c'est un bot au final) quand tu clique sur clique droit de la souris par ex.

**Comment by FinishtT** [comment]
Tu peux aussi add l'option TOP MOST. qui serait vraiment utile merci 👍

**Comment by IV2FI** [comment]
Yo ! Il y a déjà cette fonctionnalité. Le bot arrête de dessiner quand on appuie sur Echap 👍

**Comment by FinishtT** [comment]
Tu peux aussi faire un bouton qui permettra d'effacer se qu'il a dessiner ultérieurement.

**Comment by IV2FI** [comment]
Pourquoi pas, mais je pense pas que ça soit super important. Si un jour j'ai le temps !
Merci pour les suggestions en tout cas !
