### ISSUE TITLE
Impossible de créer DrawBot.exe (WinRAR)

### ISSUE THREAD

**Issue by Namathieu** [IV2FI/DrawBot#6]
<img width="335" alt="2021-04-01 19_01_25-WinRAR _ Messages de diagnostique" src="https://user-images.githubusercontent.com/73374838/113362632-ca758980-931c-11eb-8b59-f2eb9c5f1faf.png">

Voici l'erreur ^^' Est-ce un bug de la Matrix? x)

**Comment by IV2FI** [comment]
Peut-être l'antivirus qui fait des siennes ? Je ne sais pas honnêtement, jamais eu cette erreur de ma vie :(
Test avec autre chose que WinRAR peut-être

**Comment by matthieubecker57** [comment]
yes , l'antivirus le supprime automatiquement
