### ISSUE TITLE
Les couleurs ne se mettent pas

### ISSUE THREAD

**Issue by Harry007fv** [IV2FI/DrawBot#7]
Quand je clique sur l'option dessiner ca marche mais les couleurs se mettent pas c'est toujours une seul couleurs

**Comment by IV2FI** [comment]
As tu bien fait le set up décrit dans la vidéo tuto trouvable dans le read me ?
Il y a un raccourci pour stopper le bot, il suffit d'appuyer sur échap

**Comment by Harry007fv** [comment]
> As tu bien fait le set up décrit dans la vidéo tuto trouvable dans le read me ?
> 
> Il y a un raccourci pour stopper le bot, il suffit d'appuyer sur échap

j'ai fait les coordonnée dans le garticoordinate mais c'est toujours que du noirs comme couleurs

**Comment by Harry007fv** [comment]
> As tu bien fait le set up décrit dans la vidéo tuto trouvable dans le read me ?
> 
> Il y a un raccourci pour stopper le bot, il suffit d'appuyer sur échap

nan c'est bon j'ai du relancer et ca a marcher

**Comment by IV2FI** [comment]
Tu as bien redémarré le bot ? Généralement ce genre de problème vient d'un mauvais set up ou d'un oubli de redémarrage du bot une fois le set up fini. Sinon essaye de réduire la vitesse peut-être

**Comment by IV2FI** [comment]
Cool parfait !
